version: 0.0
Resources:
    - TargetService:
          Type: AWS::ECS::Service
          Properties:
              TaskDefinition: <TASK_DEFINITION>
              LoadBalancerInfo:
                  ContainerName: api
                  ContainerPort: 3000
              CapacityProviderStrategy:
                  - Base: 0
                    CapacityProvider: FARGATE_SPOT
                    Weight: 1
