version: '3.7'

volumes:
    development-db-data:
networks:
    development-network:

services: 
    development-db:
        build:
            context: ./db
        ports: 
            - '5432:5432'
        tty: true
        volumes:
            - development-db-data:/var/lib/postgresql/data
        networks:
            - development-network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: s0tetsu-L@b-v3
            POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'